version: '3.1'

services:

# postgresql:
#  container_name: postgres-sql
#  image: postgres
#  environment:
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: 1111
#   PGDATA: /data/postgres
#  volumes:
#   - /var/lib/postgresql/data
#  ports:
#   - "1234:5432"
#  networks:
#   - social-network-app
#  restart: unless-stopped

 social-network-discovery-service:
  build: ./discovery
  container_name: social-network-discovery-service
  image: marouane01/social-networks-automatisation-devops_social-network-discovery-service:discovery-image

  ports:
   - '8761:8761'
  expose:
   - '8761'
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
   interval: 10s
  networks:
   - postgres

 social-network-auth-service:
  build: ./auth-service
  container_name: social-network-auth-service
  image: marouane01/social-networks-automatisation-devops_social-network-auth-service:auth-image

  ports:
   - '8101:8101'
  expose:
   - '8101'
  networks:
   - postgres
  depends_on:
   - social-network-geteway-service

 social-network-geteway-service:
  build: ./geteway
  container_name: social-network-geteway-service
  image: marouane01/social-networks-automatisation-devops_social-network-geteway-service:gateway-image

  ports:
   - '8222:8222'
  expose:
   - '8222'
  networks:
   - postgres
  depends_on:
   - social-network-discovery-service

 social-network-friend-service:
   build: ./Friend-service
   container_name: social-network-friend-service
   image: marouane01/social-networks-automatisation-devops_social-network-friend-service:friend-image

   ports:
    - '8078:8078'
   expose:
    - '8078'
   networks:
    - postgres
   depends_on:
    - social-network-geteway-service

 social-network-interaction-service:
  build: ./interaction-service
  container_name: social-network-interaction-service
  image: marouane01/social-networks-automatisation-devops_social-network-interaction-service:interaction-image

  ports:
   - '8070:8070'
  expose:
   - '8070'
  networks:
   - postgres
  depends_on:
   - social-network-geteway-service

 social-network-media-service:
  build: ./media-service
  container_name: social-network-media-service
  image: marouane01/social-networks-automatisation-devops_social-network-media-service:media-image

  ports:
   - '8016:8016'
  expose:
   - '8016'
  networks:
   - postgres
  depends_on:
   - social-network-geteway-service

 social-network-user-service:
  build: ./User-service
  container_name: social-network-user-service
  image: marouane01/social-networks-automatisation-devops_social-network-user-service:user-image

  ports:
   - '8083:8083'
  expose:
   - '8083'
  networks:
   - postgres
  depends_on:
   - social-network-geteway-service

networks:
 postgres:
  driver: bridge
  external: true
