eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: interactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/interactions/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: comments
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: shareds
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/shareds/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: reactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/reactions/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: users-auth
          uri: http://localhost:8101
          predicates:
            - Path=/api/v1/auth/**
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"


        - id: users-data
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: medias
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/medias/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: friend-services
          uri: http://localhost:8078
          predicates:
            - Path=/api/friend/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: post-services
          uri: http://localhost:8074
          predicates:
            - Path=/api/v1/post/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                allowedOrigins: "*"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: "true"

        - id: notification-service
          uri: http://localhost:8111
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
            - name: CorsFilter
              args:
                  allowedOrigins: "*"
                  allowedMethods: "GET,POST,PUT,DELETE"
                  allowedHeaders: "*"
                  allowCredentials: "true"


#/api/friend-requests
    discovery:
      enabled: true
    config:
      enabled: false


management:
  tracing:
    sampling:
      probability: 1.0





