eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    redis:
      host: jdbc:redis://localhost/0
      port: 6379
  application:
    name: feeds

server:
  port: 8085

management:
  tracing:
    sampling:
      probability: 1.0
